name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Gestion d’état
  provider: ^6.0.0

  # Icônes iOS
  cupertino_icons: ^1.0.8

  # Police Google
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #assets:
  #  - assets/fonts
  #  - assets/images

  #fonts:
  #  - family: Poppins
  #    fonts:
        #- asset: assets/fonts/Poppins-Regular.ttf
        #- asset: assets/fonts/Poppins-Bold.ttf
        #  weight: 700

  # ↓ Ajoute ici tes assets ou polices le jour où tu en as besoin
  # assets:
  #   - assets/images/
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
